# Generated by Django 5.2.7 on 2025-10-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('address', models.TextField(max_length=100, verbose_name='Correo Electrónico')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Sueldo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='Imagen')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvitae', verbose_name='Currículum Vitae')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Moficación')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
