# Generated by Django 5.2.7 on 2025-10-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_type_employe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='address',
            field=models.TextField(max_length=500, verbose_name='Dirección'),
        ),
    ]
